name: ☣️ Regression
description: Report a regression you've observed in a newer version of Dekart
title: "[Regression] <title>"
labels: ["bug", "regression", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this regression report!
  - type: checkboxes
    attributes:
      label: Is this a regression in a recent version of Dekart?
      description: >
        A regression is when documented functionality works as expected in an older version of Dekart,
        and no longer works after upgrading to a newer version of Dekart
      options:
        - label: I believe this is a regression in Dekart functionality
          required: true
        - label: I have searched the existing issues, and I could not find an existing issue for this regression
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected/Previous Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If applicable, log output to help explain your problem.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
      value: |
        - OS:
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: database
    attributes:
      label: Which database adapter are you using with Dekart?
      description: If the bug is specific to the database or adapter, please add the label 'database adapter'
      multiple: true
      options:
        - BigQuery
        - Athena
        - Snowflake
        - CSV
        - GeoJSOn
        - other (mention it in "Additional Context")
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
