name: Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Client unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: nodetest
      - name: Server unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: gotest
      - name: Server Build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: gobuilder
      - name: Client Build
        uses: docker/build-push-action@v2
        with:
          context: .
          target: nodebuilder

          
