name: Test

on:
  pull_request:
    branches:
      - '**'
env:
  DEKART_POSTGRES_PASSWORD: dekart
  DEKART_POSTGRES_USER: postgres
  DEKART_POSTGRES_DB: dekart
  GOOGLE_APPLICATION_CREDENTIALS: GOOGLE_APPLICATION_CREDENTIALS.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Client unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: nodetest
          cache-from: type=gha,scope=dekart
          cache-to: type=gha,mode=max,scope=dekart
      - name: Server unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: gotest
          cache-from: type=gha,scope=dekart
          cache-to: type=gha,mode=max,scope=dekart
      - name: E2E build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          outputs: type=docker,dest=/tmp/e2etest.tar
          load: true
          tags: e2etest
          target: e2etest
          cache-from: type=gha,scope=dekart
          cache-to: type=gha,mode=max,scope=dekart
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: e2etest
          path: /tmp/e2etest.tar      
  bigquery:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ env.DEKART_POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.DEKART_POSTGRES_USER }}
          POSTGRES_DB: ${{ env.DEKART_POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
        ports:
          - 5432:5432
    steps:
      - name: Create google credentials
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: e2etest
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/e2etest.tar
          docker image ls -a        
      - name: E2E test BigQuery
        run: |
          docker run -i \
            --network="host" \
            -v $(pwd)/$GOOGLE_APPLICATION_CREDENTIALS:/dekart/$GOOGLE_APPLICATION_CREDENTIALS \
            -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
            -e DEKART_POSTGRES_USER=$DEKART_POSTGRES_USER \
            -e DEKART_POSTGRES_PASSWORD=$DEKART_POSTGRES_PASSWORD \
            -e DEKART_POSTGRES_PORT=$DEKART_POSTGRES_PORT \
            -e DEKART_POSTGRES_HOST=localhost \
            -e DEKART_BIGQUERY_PROJECT_ID=dekart-dev \
            -e DEKART_CLOUD_STORAGE_BUCKET=dekart-dev \
            -e DEKART_ALLOW_FILE_UPLOAD=1 \
            -e TEST_SPEC=cypress/e2e/bq \
            e2etest:latest
