name: tests

on: [workflow_call]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Client unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: nodetest
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GH_TOKEN }}" > .npmrc
          echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Client unit test
        uses: docker/build-push-action@v2
        with:
          context: .
          target: nodetest
